const fs = require('fs');
const path = require('path');


const LOREM_IPSUM = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut convallis orci. Donec euismod quam nec gravida lacinia. Aenean elit neque, fermentum nec ipsum vel, rhoncus consectetur nisi. Vestibulum ornare urna risus, ac pulvinar urna venenatis non. Donec quis lacinia magna. Vestibulum scelerisque bibendum dapibus. Fusce sollicitudin sagittis mauris, at tempor leo hendrerit ut. Suspendisse et pellentesque mauris, eget vulputate leo. Suspendisse potenti. Maecenas tincidunt interdum est, pellentesque congue risus mollis in. In viverra quam sed augue aliquet, quis tempus tellus interdum. Quisque non luctus magna, et sollicitudin elit. Pellentesque consequat libero urna, posuere aliquet massa suscipit sit amet.

Pellentesque ut imperdiet lacus. Sed efficitur, metus malesuada interdum consequat, nulla turpis iaculis risus, et hendrerit mauris nisl eu arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis eu ex vitae sem facilisis pellentesque in ut ipsum. Nam molestie pulvinar lectus in accumsan. Suspendisse luctus lectus eu sapien porta euismod. Donec vel massa eu metus suscipit molestie. Nam fermentum diam leo, ac tincidunt libero volutpat nec. Sed eget nibh arcu. Aenean placerat malesuada libero. Sed eget blandit ipsum.

Phasellus sit amet augue pellentesque, pellentesque elit et, varius nisi. Curabitur id est ante. Nulla neque ipsum, fringilla non erat et, accumsan condimentum felis. Vestibulum in mi pharetra, congue quam nec, posuere nibh. Aenean dignissim pharetra neque, eu pellentesque mi. Nulla quis ligula quis justo ornare rhoncus a non leo. Quisque eleifend scelerisque neque, vel vehicula odio imperdiet vitae.

Donec et ligula congue, posuere massa sed, mattis dolor. Suspendisse vehicula cursus pharetra. Donec eu magna ac risus mattis varius sed quis leo. Nam velit tortor, eleifend ut neque non, maximus feugiat justo. Etiam semper imperdiet diam, in semper tortor mollis quis. Morbi orci risus, tempus eget nulla eu, vehicula rhoncus tortor. Quisque a mattis lectus. Nulla facilisi.

Integer cursus ut nibh sed eleifend. Donec et varius diam. Integer accumsan nisi in dolor eleifend gravida. Maecenas semper ipsum ipsum, a aliquet risus tempor sed. Aliquam nunc arcu, porta in diam a, pellentesque cursus sapien. Etiam mi neque, congue consequat diam malesuada, suscipit bibendum neque. Donec velit felis, efficitur a velit vel, vulputate tincidunt ligula. Sed cursus egestas tellus in convallis. Nulla tristique lorem quam.

Curabitur vel orci nisi. Duis et volutpat nisl. Phasellus eu ultricies mi, a ultricies orci. Curabitur non ex justo. Integer metus magna, posuere eget ullamcorper nec, condimentum ullamcorper ligula. Ut facilisis laoreet tortor, eu varius turpis tempus id. Etiam a ultricies arcu. Nam nec arcu in libero pharetra tincidunt. Aenean placerat arcu id scelerisque varius. Integer suscipit, nibh id vestibulum suscipit, sapien ex mollis ex, quis venenatis diam diam a lacus.

Pellentesque fermentum leo a risus cursus cursus. Quisque eu enim leo. In tristique velit lacus, sit amet mattis nisi tempus quis. Ut blandit gravida erat interdum sagittis. Nunc odio ipsum, convallis eu ligula id, blandit commodo leo. Etiam id hendrerit nunc. Aliquam facilisis semper mi, sed faucibus urna scelerisque sed. Nam tempor enim id ante rutrum, non imperdiet diam rutrum. Vivamus dolor ligula, porta vitae diam et, blandit faucibus ligula.

Praesent gravida interdum lorem, convallis hendrerit odio. In auctor urna ac magna feugiat gravida. Nunc sodales enim turpis, ut bibendum felis tristique in. Vivamus in maximus nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis posuere sem vitae mauris hendrerit sagittis. Phasellus at aliquet elit. Cras nec cursus quam.

Sed convallis porta dui, vel venenatis leo luctus et. Ut ac quam ligula. Pellentesque tristique egestas lectus. Phasellus a viverra nunc, vehicula laoreet risus. Curabitur faucibus velit dolor, at mattis augue mollis vel. Pellentesque ultrices consequat mi. Suspendisse sit amet congue dolor. Maecenas laoreet euismod rhoncus. Mauris sit amet odio tristique, pulvinar lorem ac, convallis massa. Suspendisse maximus erat ut ultrices ultrices. Sed eget mollis erat. Fusce tempus augue quis varius maximus. Aenean orci orci, porta eget elit ut, imperdiet rhoncus nisl.

Ut laoreet ipsum a sapien porttitor, eu molestie leo dictum. Morbi commodo nisl eu libero sollicitudin accumsan. Cras sed cursus sapien. Sed consectetur et est at maximus. Aenean in lectus sollicitudin, varius diam eget, ullamcorper urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris varius nisl eros, a lobortis odio ornare vel. Nunc gravida at sapien eu ultricies.

Maecenas porta est ante, vitae pellentesque dui hendrerit sagittis. Maecenas sed turpis id velit dapibus varius. Sed eget sapien vitae tortor vestibulum congue. Quisque sit amet ex quis felis semper rhoncus. Praesent at aliquam leo, a sodales nisl. Vestibulum placerat, eros nec vulputate varius, lacus enim tempus ipsum, quis molestie quam erat eget augue. Nullam gravida sollicitudin justo sed fermentum. Vivamus vitae semper ipsum. Vivamus a libero non nibh aliquam facilisis a sed ante. Vivamus bibendum tortor vel neque finibus, vel eleifend massa scelerisque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras at mattis mi, maximus aliquet sapien. Nullam sit amet leo est. Vivamus sit amet aliquet ipsum, et faucibus justo. In metus sapien, ultricies lacinia felis sed, pretium fermentum nulla.

Quisque a semper nisl. Suspendisse ut nisl at massa egestas maximus. Donec at urna eget eros commodo sagittis. Pellentesque mattis lacus ante, non ullamcorper lorem pretium nec. Mauris aliquam eleifend nulla vitae laoreet. Nunc consectetur ante a nisi auctor, at molestie nisi gravida. Mauris semper, est at suscipit vestibulum, augue dolor maximus libero, eu pellentesque nisi dolor vel orci. Nam ligula lectus, pretium euismod lorem sit amet, commodo rutrum enim. Aenean augue urna, semper a ipsum eget, aliquet pretium quam. In enim libero, iaculis ac mollis lacinia, accumsan quis nibh. Curabitur suscipit ante turpis, ultricies tincidunt sapien pellentesque sed.

Nulla id efficitur ex, non dictum mi. Aenean tempus nibh lectus, commodo sodales sapien ullamcorper nec. Duis posuere rutrum odio eu vehicula. Etiam non turpis ut massa molestie aliquam. Integer lobortis lacinia sem, vitae laoreet urna accumsan quis. Ut efficitur sed turpis et sollicitudin. Donec non diam quis diam pulvinar ultrices. Vivamus pellentesque ac elit at vehicula. Aliquam erat volutpat. Nunc lacinia lorem eget commodo congue. Duis tincidunt pellentesque feugiat.

Proin ac odio mi. Vestibulum interdum dapibus luctus. Duis sit amet leo rutrum, dictum nibh id, gravida magna. Suspendisse viverra scelerisque sem nec sollicitudin. Mauris at imperdiet risus, eget porttitor ante. Praesent luctus magna a cursus porttitor. In efficitur, nisi vitae porta fringilla, dolor risus imperdiet quam, nec finibus odio turpis non purus. Praesent scelerisque dolor maximus interdum pellentesque. Integer quis purus id augue sagittis sollicitudin vitae vitae quam. Curabitur semper malesuada eros, quis posuere ipsum interdum sed. Sed ex arcu, laoreet at finibus sed, condimentum in ipsum.

Suspendisse potenti. Phasellus nec lectus elementum ligula euismod elementum. Nunc laoreet dictum urna eget rhoncus. Proin viverra elementum elit, eget ultrices nisi. Donec facilisis sollicitudin elit, ut consectetur quam. Aenean tristique vehicula laoreet. Vestibulum ut venenatis dui.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam euismod, magna vel consectetur auctor, nibh lectus consequat mi, ut laoreet elit mi ac mauris. Nunc iaculis diam lacinia ligula finibus, nec sollicitudin dui pharetra. Curabitur ac mollis lectus. Nullam posuere justo vel turpis ornare semper a vitae massa. Aliquam et dui eget purus aliquet lobortis. Phasellus at justo id ipsum faucibus congue. Fusce condimentum nibh sed massa pellentesque, eu consectetur nunc fringilla. Nunc vestibulum lacinia vulputate. Donec vitae tellus neque.

Morbi vel ornare diam. Etiam euismod aliquet ante. Nullam pellentesque, dolor in commodo accumsan, erat justo facilisis metus, a ullamcorper ex lectus a velit. Sed odio enim, mattis vel mauris et, pulvinar dignissim metus. Donec eu dignissim dolor. Pellentesque maximus ipsum quis urna semper vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed convallis neque quis leo euismod vulputate rutrum sit amet massa.

Donec laoreet lorem sed imperdiet ultricies. Mauris a molestie lectus. Integer pretium enim in ex tempor feugiat. Donec posuere magna non tincidunt luctus. Cras dolor nisi, blandit tincidunt auctor eu, vehicula nec arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque convallis ipsum vitae condimentum egestas. Suspendisse maximus tellus sed dui feugiat, non consequat neque aliquet. Maecenas id porta eros, eget faucibus augue. Mauris vestibulum lacus sed tellus maximus, ut lacinia neque egestas. Nullam dictum orci et mi egestas, tincidunt lacinia risus eleifend. Phasellus lacus urna, tincidunt vel porta mattis, iaculis id eros. Nullam at neque lacinia, lobortis velit non, maximus sem. Vivamus porttitor dapibus aliquam.

Maecenas arcu ipsum, facilisis vel venenatis id, gravida a lacus. Integer congue molestie libero quis euismod. Donec commodo tincidunt velit et tempus. Maecenas lacinia convallis blandit. Duis dapibus gravida risus eget lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur at mollis odio. Fusce eleifend ac elit luctus elementum. Aenean viverra posuere sem, sit amet vehicula tortor fermentum sed. In ullamcorper neque at mauris porta ultrices. Vivamus sit amet est ut odio suscipit egestas. Fusce pretium eros metus, eget euismod lectus tincidunt sit amet. Aliquam rutrum risus sit amet orci finibus fermentum.

Morbi varius orci non sem accumsan tincidunt. Nulla sed fermentum metus. Mauris vitae rutrum risus. Quisque in odio id quam luctus feugiat. In at volutpat lorem. Fusce at vestibulum lorem. Nulla volutpat condimentum egestas. Praesent a scelerisque nisl. Morbi sollicitudin velit eu est tincidunt, eu malesuada arcu rutrum. In magna orci, venenatis non ligula id, suscipit egestas arcu. Nullam vitae dictum libero.

Aenean vitae condimentum arcu. Integer feugiat tincidunt nunc, non viverra libero ultrices vel. Ut sem lectus, ultricies quis efficitur eget, aliquet ac mauris. Nulla eu purus pellentesque, pharetra enim non, feugiat velit. Ut luctus gravida orci non gravida. Donec vestibulum pellentesque auctor. Curabitur maximus, lorem vel ultricies volutpat, sapien orci luctus quam, at faucibus nulla purus a massa. Sed id placerat enim. Proin a dolor fringilla, consequat sapien eget, posuere orci. Donec a tincidunt libero. Nullam in metus posuere, venenatis odio a, pulvinar magna. Quisque a magna vitae enim finibus mattis. Integer molestie sapien vitae leo sagittis suscipit. Phasellus dolor nisi, hendrerit ultrices varius mollis, porta sed ipsum. Curabitur tempor ante magna, quis accumsan sapien maximus in. Integer quis varius turpis.

Aliquam varius feugiat porta. Donec lobortis mauris eget nisl interdum, sed imperdiet lacus tincidunt. Praesent eu dolor quis nulla fermentum cursus at viverra sem. Phasellus non porttitor nibh. Vivamus ac imperdiet nisi. Proin eleifend elit vel neque fermentum, sed aliquet ligula vestibulum. Duis blandit, velit sit amet congue elementum, risus diam accumsan mi, a aliquam odio elit consequat lectus. Donec ac malesuada dolor, eget finibus diam. Maecenas tincidunt, ipsum quis auctor tristique, dolor purus hendrerit magna, sit amet sagittis orci libero quis nibh. Donec ipsum nisi, aliquet a mattis ut, facilisis sollicitudin nibh. Quisque nunc nisi, pellentesque in est at, varius laoreet magna. Aliquam erat volutpat.

Ut lobortis cursus dictum. Nam pretium fringilla velit, sit amet tincidunt massa malesuada at. Curabitur condimentum lorem et erat iaculis iaculis id a dui. Aliquam tristique, felis nec vestibulum sagittis, dolor lacus finibus metus, vitae blandit purus felis vitae purus. Maecenas id magna metus. Pellentesque id pretium ante. Aenean id fermentum urna, at sagittis lorem. Suspendisse et elementum nulla. Sed feugiat, massa at sagittis fermentum, nunc augue imperdiet ligula, nec ornare libero ex quis nulla. Praesent eu ante maximus, rhoncus felis non, tempor est. Proin vestibulum congue velit, quis laoreet massa. Aliquam dapibus mattis lacus et convallis.

Ut vitae cursus sem. Cras interdum gravida velit eget tincidunt. Aliquam dui nibh, iaculis at eros vel, finibus feugiat odio. Donec libero ante, rutrum eget tellus in, tristique volutpat metus. Vestibulum sodales enim nec ex venenatis dictum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla volutpat, nibh vitae molestie ullamcorper, elit mi feugiat dolor, in finibus risus tortor in purus. Etiam gravida nisi sed nisi vulputate commodo. Maecenas elementum quam vitae erat mattis, nec fringilla leo porta. Phasellus mauris odio, malesuada id consectetur vitae, aliquet a libero. Aliquam erat volutpat.

Suspendisse ac tincidunt erat, at cursus mi. Aenean faucibus congue ex id pretium. Etiam ut enim nec turpis gravida pretium. Phasellus convallis sem quis tincidunt blandit. Sed eget augue vulputate, consequat magna eget, viverra augue. Mauris non sapien quis lacus faucibus tincidunt ac vel turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porttitor maximus massa, vel iaculis arcu. Nunc venenatis egestas iaculis. Nullam finibus nisi ac felis ultrices iaculis. In malesuada, ipsum non volutpat posuere, magna nisi gravida felis, ut tempor tortor lorem vel eros. Sed facilisis rhoncus nulla, ac molestie lectus congue a. Morbi purus tortor, fermentum eget laoreet et, convallis a metus. Mauris id malesuada massa. Donec et eleifend libero.

Quisque vitae quam non augue placerat sodales a sed nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc vitae suscipit urna. In dapibus ullamcorper leo quis sagittis. In ullamcorper sed sem eget laoreet. Sed mattis velit urna, sed tincidunt eros pellentesque vitae. Mauris et ipsum diam. Aliquam tincidunt nec nisl at cursus. Cras quis mi eu arcu malesuada consectetur. Vestibulum id placerat purus. Pellentesque commodo est interdum iaculis feugiat. Vestibulum auctor pellentesque nisi, ac vehicula tellus aliquet eu. Sed urna mauris, tristique vitae neque non, sollicitudin vehicula mi.

Aliquam mollis massa et maximus euismod. Quisque auctor volutpat bibendum. Cras ullamcorper lacus eu ligula rhoncus, id aliquam odio volutpat. Donec fringilla quam augue, non varius nunc facilisis quis. Morbi ac magna nec dui laoreet laoreet. Nulla suscipit enim sit amet ullamcorper laoreet. Curabitur efficitur mauris eu nisl elementum gravida. Aenean aliquet ante eu ornare pulvinar. Curabitur quis odio tristique, ullamcorper turpis non, aliquet nibh. Quisque tincidunt, odio non consectetur sodales, ante lacus rutrum diam, a semper sapien enim non dolor. Nullam aliquet viverra dolor, at rhoncus dolor vehicula eu. Suspendisse tempor, dui a efficitur lobortis, neque nibh tincidunt orci, eu tempor nisi mauris non est. Donec posuere commodo cursus. Donec elementum metus hendrerit purus rutrum sodales ut sed mi. Sed sed eros pretium, interdum lectus in, rutrum lacus.

Mauris tempus egestas quam, eu pulvinar elit sollicitudin pulvinar. Suspendisse magna tellus, consequat elementum urna eu, pulvinar porttitor urna. Nam vitae dolor eget ligula posuere malesuada. Morbi pellentesque nisl quis orci venenatis, eget luctus odio pharetra. Vivamus elit magna, venenatis quis pharetra ac, semper quis enim. Sed et fringilla velit, eget scelerisque sapien. Nullam vel neque feugiat, iaculis ligula porttitor, feugiat diam. Vivamus elementum dui velit, nec elementum dui volutpat eget. Etiam ut pellentesque massa. Donec sodales leo tincidunt tellus euismod sollicitudin. Phasellus dignissim ultricies gravida. Phasellus ac nibh ullamcorper leo tempor elementum vel quis est. Donec vitae condimentum purus, id auctor elit. Quisque mi lectus, iaculis quis lobortis ut, sagittis at est. Duis et justo nec lorem facilisis maximus vel et magna. Nunc id quam vehicula, dignissim enim et, euismod leo.

Suspendisse ultricies at quam in porta. Etiam rhoncus convallis lobortis. Cras hendrerit nisl non posuere porta. Nunc tempus porttitor est eu aliquet. Morbi ac euismod nisi. Integer eget quam a massa rutrum vestibulum. Praesent tempor, nunc quis lobortis feugiat, tellus augue dignissim risus, non congue est erat sit amet nisl. Cras scelerisque tincidunt pellentesque. Aenean lorem massa, eleifend sed mi ac, imperdiet facilisis quam. In hac habitasse platea dictumst. Sed et ante maximus, porttitor urna a, volutpat dui. Maecenas lobortis a velit ac ullamcorper. Aliquam semper ac odio hendrerit venenatis. Curabitur et ultricies nibh, ac dictum massa.

Quisque in sapien lobortis, tincidunt eros in, euismod ligula. Mauris scelerisque in odio non ullamcorper. Nulla ultricies tempus purus, et tincidunt enim rutrum in. Nam porta felis sed augue euismod, nec rutrum leo suscipit. Aliquam sed dui quis metus venenatis consequat vel et massa. Praesent non imperdiet ex. Nam nulla ipsum, consectetur at sapien ac, dignissim laoreet elit. Curabitur accumsan molestie ipsum, id consequat odio. Sed turpis enim, euismod sed diam eleifend, volutpat viverra est. Aenean tempor luctus velit vitae mattis. Morbi at mauris sed ante iaculis ornare eu a nulla.

Quisque facilisis sollicitudin ante ac dapibus. Integer consequat mi ut lectus pharetra, ac auctor nisl dignissim. Quisque semper justo fringilla tortor dictum varius. Praesent massa est, tempus eget ante vel, pretium elementum magna. Nullam nec ante at justo scelerisque efficitur sed eget felis. Donec pulvinar pellentesque sapien non placerat. Maecenas consectetur elit quis ante consequat mattis. Mauris nisl diam, lobortis vitae tortor sit amet, egestas maximus diam. In sollicitudin auctor nulla, ut ullamcorper diam consectetur at. Duis eu mi viverra, aliquam velit at, fermentum augue. Mauris lobortis pulvinar lectus non porttitor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi non erat nec lacus suscipit euismod at at tortor. Praesent ultricies sollicitudin iaculis. Quisque iaculis suscipit ex, vitae rhoncus tortor accumsan id.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque ut convallis nunc. Nunc placerat nisl ut tempus suscipit. Sed lectus leo, dictum dignissim sem in, blandit rhoncus eros. Curabitur convallis diam eu imperdiet imperdiet. Praesent in massa euismod, laoreet magna id, lobortis ligula. Curabitur semper iaculis porta. Quisque dapibus magna aliquam ullamcorper ornare. Aliquam erat volutpat. Vestibulum quam massa, molestie vitae finibus at, laoreet scelerisque dui. In aliquet, leo vel suscipit malesuada, dolor sem semper nulla, et posuere arcu nunc at est. Quisque eget porttitor augue.

Pellentesque nulla arcu, dictum eget condimentum vel, cursus vel quam. Nam ut consequat arcu. Pellentesque nec elementum velit. Ut et porta ligula. Vestibulum imperdiet magna lacinia, mollis nulla ut, placerat turpis. Nulla scelerisque tortor ut massa vehicula, eu pretium metus iaculis. Nullam metus dolor, semper vitae tempor sed, lacinia ut risus. Etiam id diam ac turpis sodales rutrum nec nec enim. Quisque ipsum dui, egestas quis dui vel, euismod feugiat libero. Nulla scelerisque convallis ante, ac imperdiet orci ultrices ut. Vestibulum ac turpis sed libero convallis varius ut dictum elit. Donec ac tellus felis. Vivamus congue libero et massa fermentum laoreet. Ut mattis luctus elementum.

Fusce dapibus tempor nunc quis rhoncus. In pellentesque nulla non mi sodales, ut accumsan risus cursus. Donec vestibulum lorem sed fermentum rhoncus. Duis at diam nec mi tristique mattis. Sed vitae quam porta eros pretium viverra venenatis eget risus. Donec gravida ac eros a feugiat. Aenean eleifend mi ut lectus pharetra, nec sollicitudin orci tempus.

Morbi ac eros non lacus sagittis cursus sit amet eu nibh. Integer dapibus ex a sapien lacinia scelerisque. Nullam vel malesuada mi. Proin sit amet vestibulum nibh, et ornare nisi. Aliquam non enim efficitur sapien vulputate laoreet. Integer rutrum turpis eu ante volutpat, sit amet tempor urna rhoncus. Mauris sodales massa eu augue tempor congue. Suspendisse luctus, diam a imperdiet vestibulum, purus sem tempus erat, vitae tristique ex metus at dolor. Nam rutrum libero ipsum, molestie faucibus dolor dapibus pharetra. Duis vel faucibus tortor, sed porttitor quam. Phasellus malesuada varius ex, at fringilla odio convallis at. Nullam non consequat nisl. Aenean pretium sem ut erat ultrices, nec auctor lacus condimentum. Sed imperdiet tincidunt libero eu mollis.

Suspendisse in nisl aliquam nibh pulvinar congue sed at ante. Phasellus et lobortis orci. Sed ut pharetra augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla iaculis purus elit, in egestas erat porttitor eu. In luctus porta convallis. Morbi facilisis condimentum risus ac cursus. Ut eu consectetur est, eget auctor eros.

Nulla facilisi. Nullam semper vel neque ac facilisis. Donec tincidunt ut lacus non blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nam id nulla est. Etiam lacus enim, consequat eu dolor sed, fermentum pharetra justo. Nullam lectus dui, pulvinar vel malesuada a, volutpat ut lectus. Quisque id maximus justo.

Sed laoreet accumsan eros laoreet vehicula. Mauris feugiat nulla nec ante bibendum, in ornare urna placerat. Nulla commodo justo eu est gravida consequat. Maecenas risus nisl, faucibus in mauris id, eleifend molestie purus. Donec tristique, risus sit amet aliquet convallis, tellus orci dignissim purus, eget lobortis ante ipsum sed dolor. In dui neque, pellentesque ut finibus id, suscipit ut justo. Donec volutpat quam eget elementum rhoncus. Morbi mi sapien, congue ut sapien sed, venenatis aliquam quam. Nam lacinia venenatis nunc. Duis condimentum turpis id ex tincidunt, non porta nisl gravida. Nam malesuada, magna at accumsan rhoncus, ex libero iaculis ex, a tristique urna est sed mauris.

Vivamus gravida congue ante sit amet imperdiet. Nulla vel elit magna. Morbi magna diam, convallis ac lectus in, venenatis pulvinar tellus. Cras porttitor, enim et aliquet scelerisque, nisi urna consectetur leo, nec malesuada orci orci ut metus. Vestibulum tincidunt felis a nisl fringilla pretium. Mauris ac dui in lectus fermentum suscipit non sit amet mi. Sed non augue accumsan, tincidunt quam vel, lacinia leo. Cras enim augue, congue eget risus in, semper sodales quam. Maecenas tincidunt enim ante, a suscipit augue viverra vitae. Mauris luctus purus ut sapien rutrum ullamcorper.

Nullam lacus ante, dignissim nec est ac, maximus tristique dolor. Sed a blandit neque. Maecenas gravida, erat eget accumsan pulvinar, augue magna semper ante, id pellentesque diam diam ac metus. Pellentesque vehicula nulla ut risus sodales varius. In ultrices justo sit amet urna tempus aliquet. Sed luctus neque sit amet sapien consectetur, sit amet dignissim neque pulvinar. Proin porta ullamcorper volutpat. In sit amet interdum felis. Donec vehicula nisl id lorem tristique, id suscipit arcu luctus. Aenean condimentum magna velit. Integer nisl lacus, hendrerit a mollis eget, consequat vel nibh. Suspendisse quis ante aliquet, luctus sapien ac, sodales risus. Suspendisse dui risus, lacinia ac vulputate sed, efficitur non ante. Pellentesque quis magna pharetra purus cursus feugiat. Nunc et est at est condimentum eleifend quis eu nunc.
`;

module.exports = function (gulp) {
  
  gulp.task('gen-markdown-posts', function () {
    
    var qtty = 50;
    
    var targetDir = path.join(__dirname, '../tmp/markdown-project/posts');
    
    while (qtty > 0) {
      
      var filepath = qtty < 10 ?
        path.join(targetDir, 'post-0' + qtty + '.md') :
        path.join(targetDir, 'post-' + qtty + '.md');
      
      fs.writeFileSync(
        filepath,
        [
          '---',
          'title: post-' + qtty,
          '---',
          'content-' + qtty,
          // LOREM_IPSUM,
        ].join('\n'),
        'utf8'
      );
      
      qtty -= 1;
    }
    
  });
  
};
